variable avail_zone {}
variable env_prefix {}
variable vpc_id {}
variable public_key {}
variable public_key_location {}
variable private_key {}
variable my_ip {}
variable instance_type {}
variable image_name {}
variable subnet_id {}